# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 042b60c778873bf7c296bf689fe6abbcba340cb4adcd30f7393f0aa0ec8994c918829aa9e5901fda06d62212999c689327ae246e81fc2ae7192abe2ce66dac98

test:
  secret_key_base: f13f3c2f73e77c952987f52e736b87017587716c9c8c54f4e3bb216f013b661d021ff8ebcacd749f28bf9ff63360199a505a214a420216153740bd5fc099fb2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
